#!/usr/bin/env python3
"""Generate a Unity-free stub of UIStyleTokens for the icon-preview harness.

The real UIStyleTokens parses its hex colours through ColorUtility (native) and
depends on TextMeshPro, so it cannot load outside Unity. This script extracts every
`public static readonly Color Name = Hex("#RRGGBB[AA]");` inside each nested static
class and emits the same class shape with a managed hex parser, so the icon drawing
code compiles against the identical palette without duplicating any values by hand.
"""

import re
import sys
from pathlib import Path

CLASS_RE = re.compile(r"^\s*public static class (\w+)\s*$")
COLOR_RE = re.compile(r'^\s*public static readonly Color (\w+) = Hex\("(#[0-9A-Fa-f]{6}(?:[0-9A-Fa-f]{2})?)"\);\s*$')


def main(source: Path, target: Path) -> int:
    lines = source.read_text(encoding="utf-8-sig").splitlines()
    classes: dict[str, list[tuple[str, str]]] = {}
    current = None
    for line in lines:
        class_match = CLASS_RE.match(line)
        if class_match:
            name = class_match.group(1)
            current = None if name == "UIStyleTokens" else name
            if current:
                classes.setdefault(current, [])
            continue
        color_match = COLOR_RE.match(line)
        if color_match and current:
            classes[current].append((color_match.group(1), color_match.group(2)))

    out = [
        "// <auto-generated> by tools/icon-preview/generate_style_stub.py from",
        f"// {source.as_posix()}. Do not edit; regenerate by building the harness.",
        "using UnityEngine;",
        "",
        "namespace FungusToast.Unity.UI",
        "{",
        "    public static class UIStyleTokens",
        "    {",
    ]
    for class_name, colors in classes.items():
        if not colors:
            continue
        out.append(f"        public static class {class_name}")
        out.append("        {")
        for name, hex_value in colors:
            out.append(f'            public static readonly Color {name} = Hex("{hex_value}");')
        out.append("        }")
        out.append("")
    out += [
        "        public static Color WithAlpha(Color color, float alpha)",
        "        {",
        "            color.a = alpha;",
        "            return color;",
        "        }",
        "",
        "        private static Color Hex(string html)",
        "        {",
        "            string h = html.TrimStart('#');",
        "            float r = System.Convert.ToInt32(h.Substring(0, 2), 16) / 255f;",
        "            float g = System.Convert.ToInt32(h.Substring(2, 2), 16) / 255f;",
        "            float b = System.Convert.ToInt32(h.Substring(4, 2), 16) / 255f;",
        "            float a = h.Length >= 8 ? System.Convert.ToInt32(h.Substring(6, 2), 16) / 255f : 1f;",
        "            return new Color(r, g, b, a);",
        "        }",
        "    }",
        "}",
        "",
    ]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(out), encoding="utf-8")
    total = sum(len(c) for c in classes.values())
    print(f"Wrote {target} ({total} colours in {len(classes)} groups).")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("usage: generate_style_stub.py <UIStyleTokens.cs> <output.cs>")
        sys.exit(2)
    sys.exit(main(Path(sys.argv[1]), Path(sys.argv[2])))
