using FungusToast.Core.AI;
using FungusToast.Core.Mutations;
using FungusToast.Simulation.Candidates;
using Xunit;

namespace FungusToast.Simulation.Tests.Candidates;

public sealed class CandidateRankingTests
{
    /// <summary>
    /// Ranking on the point estimate would put a noisy candidate above a steadier one that is
    /// better on the evidence, so the order comes from the conservative bound.
    /// </summary>
    [Fact]
    public void CandidatesAreOrderedByTheirConservativeBound_NotTheirPointEstimate()
    {
        var (queue, genomes, parent) = CreateField();
        // The noisy candidate has the higher estimate but a much wider interval.
        Measure(queue, 0, CandidateEvaluationStage.Comparison, estimate: 0.30, low: -0.10, high: 0.70);
        Measure(queue, 1, CandidateEvaluationStage.Comparison, estimate: 0.12, low: 0.08, high: 0.16);

        var ranked = CandidateRanking.Rank(queue, genomes, parent);

        Assert.Equal(queue.Entries[1].CandidateId, ranked[0].CandidateId);
        Assert.True(ranked[0].Strength!.ConservativeScore > ranked[1].Strength!.ConservativeScore);
        Assert.Equal(0.30, ranked[1].Strength!.Estimate);
    }

    /// <summary>
    /// A candidate is only as good as its worst context, and one context cannot demonstrate
    /// robustness at all.
    /// </summary>
    [Fact]
    public void RobustnessReportsTheWorstContextAndWhetherItWasEvenDemonstrated()
    {
        var (queue, genomes, parent) = CreateField();
        Measure(queue, 0, CandidateEvaluationStage.Comparison, estimate: 0.20, low: 0.15, high: 0.25);
        Measure(queue, 0, CandidateEvaluationStage.Holdout, estimate: 0.08, low: 0.02, high: 0.14);
        Measure(queue, 1, CandidateEvaluationStage.Comparison, estimate: 0.20, low: 0.15, high: 0.25);

        var ranked = CandidateRanking.Rank(queue, genomes, parent);
        var twoContexts = ranked.Single(row => row.CandidateId == queue.Entries[0].CandidateId);
        var oneContext = ranked.Single(row => row.CandidateId == queue.Entries[1].CandidateId);

        Assert.Equal(2, twoContexts.Robustness!.ContextsMeasured);
        Assert.Equal(0.02, twoContexts.Robustness.WorstCi95Low);
        Assert.True(twoContexts.Robustness.IsDemonstrated);
        Assert.True(twoContexts.Robustness.SignConsistent);

        Assert.False(oneContext.Robustness!.IsDemonstrated);
    }

    /// <summary>
    /// An advantage that reverses between contexts did not transfer, which the sign check surfaces
    /// even though both intervals look respectable on their own.
    /// </summary>
    [Fact]
    public void AnAdvantageThatReversesBetweenContexts_IsFlaggedAsInconsistent()
    {
        var (queue, genomes, parent) = CreateField();
        Measure(queue, 0, CandidateEvaluationStage.Comparison, estimate: 0.20, low: 0.15, high: 0.25);
        Measure(queue, 0, CandidateEvaluationStage.Holdout, estimate: -0.18, low: -0.24, high: -0.12);

        var ranked = CandidateRanking.Rank(queue, genomes, parent);
        var row = ranked.Single(candidate => candidate.CandidateId == queue.Entries[0].CandidateId);

        Assert.False(row.Robustness!.SignConsistent);
        // The deepest stage is reported, and the worst context drives robustness.
        Assert.Equal(CandidateEvaluationStage.Holdout, row.Strength!.MeasuredStage);
        Assert.Equal(-0.24, row.Robustness.WorstCi95Low);
    }

    /// <summary>
    /// The four measures stay separate. A candidate that is strong but fragile must not be able to
    /// borrow rank from its strength, which is what a composite score would allow.
    /// </summary>
    [Fact]
    public void StrengthRobustnessFidelityAndDiversityAreReportedSeparately()
    {
        var (queue, genomes, parent) = CreateField();
        Measure(queue, 0, CandidateEvaluationStage.Comparison, estimate: 0.20, low: 0.15, high: 0.25);

        var row = CandidateRanking.Rank(queue, genomes, parent)[0];

        Assert.NotNull(row.Strength);
        Assert.NotNull(row.Robustness);
        Assert.InRange(row.LineageFidelity, 0.0, 1.0);
        Assert.InRange(row.BehavioralDiversity, 0.0, 1.0);
        // No composite exists to read; the type deliberately exposes none.
        Assert.Empty(typeof(CandidateRankingRow).GetProperties()
            .Where(property => property.Name.Contains("Composite", StringComparison.Ordinal)
                || property.Name.Contains("Overall", StringComparison.Ordinal)));
    }

    /// <summary>
    /// Candidates generated by a one-gene change from the same parent still play largely like it,
    /// so fidelity should be high rather than arbitrary.
    /// </summary>
    [Fact]
    public void CandidatesDerivedFromOneGeneChange_StayCloseToTheirParent()
    {
        var (queue, genomes, parent) = CreateField();

        var ranked = CandidateRanking.Rank(queue, genomes, parent);

        Assert.All(ranked, row => Assert.True(
            row.LineageFidelity > 0.5,
            $"{row.DisplayName} drifted from its parent with fidelity {row.LineageFidelity:0.###}."));
    }

    [Fact]
    public void EveryRankedCandidate_ReportsANonEmptyCategoryProfile()
    {
        var (queue, genomes, parent) = CreateField();

        foreach (var row in CandidateRanking.Rank(queue, genomes, parent))
        {
            Assert.Equal(Enum.GetValues(typeof(MutationCategory)).Length, row.CategoryProfile.Count);
            Assert.True(row.CategoryProfile.Values.Sum() > 0, $"{row.DisplayName} bought nothing.");
        }
    }

    [Fact]
    public void UnmeasuredCandidates_RankBelowMeasuredOnesRatherThanBeingDropped()
    {
        var (queue, genomes, parent) = CreateField();
        Measure(queue, 1, CandidateEvaluationStage.Smoke, estimate: 0.01, low: -0.01, high: 0.03);

        var ranked = CandidateRanking.Rank(queue, genomes, parent);

        Assert.Equal(queue.Entries.Count, ranked.Count);
        Assert.Equal(queue.Entries[1].CandidateId, ranked[0].CandidateId);
        Assert.Null(ranked.Last().Strength);
    }

    [Fact]
    public void ACategoryProfile_SumsPurchasedLevelsByCategory()
    {
        var profile = CandidateRanking.BuildCategoryProfile(new Dictionary<int, int>
        {
            [MutationIds.MycelialBloom] = 3,
            [MutationIds.HomeostaticHarmony] = 2
        });

        var bloomCategory = MutationRegistry.GetById(MutationIds.MycelialBloom)!.Category;
        var harmonyCategory = MutationRegistry.GetById(MutationIds.HomeostaticHarmony)!.Category;
        var expected = bloomCategory == harmonyCategory ? 5 : 3;
        Assert.Equal(expected, profile[bloomCategory]);
        Assert.Equal(5, profile.Values.Sum());
    }

    [Fact]
    public void RankingACandidateWithoutItsGenome_Throws()
    {
        var (queue, _, parent) = CreateField();

        Assert.Throws<ArgumentException>(() => CandidateRanking.Rank(
            queue,
            new Dictionary<string, CandidateGenome>(StringComparer.Ordinal),
            parent));
    }

    private static void Measure(
        CandidateEvaluationQueue queue,
        int entryIndex,
        CandidateEvaluationStage stage,
        double estimate,
        double low,
        double high)
    {
        queue.RecordStageResult(
            queue.Entries[entryIndex].CandidateId,
            stage,
            CandidateStageResult.Passed,
            CandidateEvaluationQueue.StageGameCost(stage),
            5,
            estimate: estimate,
            ci95Low: low,
            ci95High: high);
    }

    private static (CandidateEvaluationQueue Queue,
        IReadOnlyDictionary<string, CandidateGenome> Genomes,
        IMutationSpendingStrategy Parent) CreateField()
    {
        _ = AIRoster.TestingStrategies.Count;
        var parent = StrategyRegistry.GetDefinition(StrategySetEnum.Testing, "TST_BalancedGeneralistControl")!;
        var candidates = CandidateGenerator.Generate(new CandidateGenerationPlan
        {
            SchemaVersion = CandidateGenerationPlan.CurrentSchemaVersion,
            PlanId = "ranking",
            Purpose = "Rank a bounded opener-order search.",
            ParentStrategyId = parent.StrategyId,
            ParentStrategySet = StrategySetEnum.Testing,
            Operators = new[] { CandidateOperator.GoalOrderAdjacentSwap },
            MaximumCandidates = CandidateGenerationPlan.CandidateCeiling
        }).Accepted;

        var queue = CandidateEvaluationQueue.Create(
            "ranking-test",
            candidates,
            totalGameBudget: 5000,
            totalRuntimeBudgetSeconds: 10_000);

        return (
            queue,
            candidates.ToDictionary(candidate => candidate.CandidateId, StringComparer.Ordinal),
            parent.Strategy);
    }
}
