using System.Collections.Generic;
using FungusToast.Unity.Input;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace FungusToast.Unity.UI
{
    public enum CursorKind
    {
        Arrow,
        Hand,
        Target
    }

    /// <summary>
    /// Owns the hardware cursor for the whole game. Nothing is wired per widget: every
    /// frame the pointer is raycast through the EventSystem and the hand is shown when
    /// the top hit (or its nearest ancestor) is an interactable <see cref="Selectable"/>,
    /// so a mutation card that toggles its button off for locked/unaffordable/maxed
    /// states loses the hand for free. Board tile-selection modes push
    /// <see cref="CursorKind.Target"/> through <see cref="Push"/>/<see cref="Pop"/>, which
    /// outranks hover detection so a card hover-exit can never clobber the reticle.
    ///
    /// Textures come from Assets/Resources/UI/Cursors/ (generated by
    /// tools/cursor-gen/generate_cursors.py, imported as Cursor by
    /// CursorTextureImporter). The arrow is also the Player Settings default cursor so
    /// it applies from the first frame; hotspots here must match the generator.
    /// </summary>
    public sealed class CursorManager : MonoBehaviour
    {
        private const string ResourceFolder = "UI/Cursors/";
        private static readonly Vector2 ArrowHotspot = new(2f, 2f);
        private static readonly Vector2 HandHotspot = new(11f, 2f);
        private static readonly Vector2 TargetHotspot = new(16f, 16f);

        public static CursorManager Instance { get; private set; }

        private Texture2D arrowTexture;
        private Texture2D handTexture;
        private Texture2D targetTexture;

        // Most recent push wins. Owners are tracked so a mode can release only its own
        // request, and so requests from destroyed owners can be pruned.
        private readonly List<(object owner, CursorKind kind)> overrides = new();
        private readonly List<RaycastResult> raycastResults = new();
        private PointerEventData pointerEventData;
        private CursorKind appliedKind = CursorKind.Arrow;
        private bool cursorApplied;
        private bool applicationFocused = true;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        private static void Bootstrap()
        {
            if (Instance != null)
            {
                return;
            }

            var host = new GameObject(nameof(CursorManager));
            DontDestroyOnLoad(host);
            host.AddComponent<CursorManager>();
        }

        /// <summary>
        /// Requests <paramref name="kind"/> on behalf of <paramref name="owner"/> until the
        /// same owner calls <see cref="Pop"/>. Re-pushing for an existing owner replaces
        /// its request rather than stacking a duplicate.
        /// </summary>
        public void Push(CursorKind kind, object owner)
        {
            if (owner == null)
            {
                return;
            }

            RemoveOwner(owner);
            overrides.Add((owner, kind));
            Refresh();
        }

        public void Pop(object owner)
        {
            if (owner == null || !RemoveOwner(owner))
            {
                return;
            }

            Refresh();
        }

        private void Awake()
        {
            if (Instance != null && Instance != this)
            {
                Destroy(gameObject);
                return;
            }

            Instance = this;
            arrowTexture = Load("cursor_arrow");
            handTexture = Load("cursor_hand");
            targetTexture = Load("cursor_target");
        }

        private void Update()
        {
            Refresh();
        }

        private void OnApplicationFocus(bool hasFocus)
        {
            // Hand the cursor back to the OS while unfocused (and stop re-applying it from
            // Update while runInBackground keeps ticking); regaining focus re-applies on
            // the next Refresh because cursorApplied was cleared.
            applicationFocused = hasFocus;
            if (!hasFocus)
            {
                RestoreSystemCursor();
            }
        }

        private void OnDisable()
        {
            RestoreSystemCursor();
        }

        private void OnDestroy()
        {
            if (Instance == this)
            {
                Instance = null;
            }
        }

        private void Refresh()
        {
            if (!applicationFocused)
            {
                return;
            }

            PruneDeadOwners();
            CursorKind resolved = overrides.Count > 0
                ? overrides[overrides.Count - 1].kind
                : IsPointerOverInteractable() ? CursorKind.Hand : CursorKind.Arrow;

            if (cursorApplied && resolved == appliedKind)
            {
                return;
            }

            Apply(resolved);
        }

        private bool IsPointerOverInteractable()
        {
            EventSystem eventSystem = EventSystem.current;
            if (eventSystem == null)
            {
                return false;
            }

            pointerEventData ??= new PointerEventData(eventSystem);
            pointerEventData.position = UnityInputAdapter.GetPointerScreenPosition();
            raycastResults.Clear();
            eventSystem.RaycastAll(pointerEventData, raycastResults);
            if (raycastResults.Count == 0)
            {
                return false;
            }

            // RaycastAll sorts front-to-back, so only the top hit decides: a modal dim or
            // tooltip covering a button must not leak the hand through.
            GameObject top = raycastResults[0].gameObject;
            if (top == null)
            {
                return false;
            }

            Selectable selectable = top.GetComponentInParent<Selectable>();
            return selectable != null && selectable.IsInteractable();
        }

        private void Apply(CursorKind kind)
        {
            Texture2D texture;
            Vector2 hotspot;
            switch (kind)
            {
                case CursorKind.Hand:
                    texture = handTexture;
                    hotspot = HandHotspot;
                    break;
                case CursorKind.Target:
                    texture = targetTexture;
                    hotspot = TargetHotspot;
                    break;
                default:
                    texture = arrowTexture;
                    hotspot = ArrowHotspot;
                    break;
            }

            // A missing texture falls back to the Player Settings default (the arrow)
            // rather than leaving the previous custom cursor on screen.
            Cursor.SetCursor(texture, texture != null ? hotspot : Vector2.zero, CursorMode.Auto);
            appliedKind = kind;
            cursorApplied = true;
        }

        private void RestoreSystemCursor()
        {
            Cursor.SetCursor(null, Vector2.zero, CursorMode.Auto);
            cursorApplied = false;
        }

        private bool RemoveOwner(object owner)
        {
            bool removed = false;
            for (int i = overrides.Count - 1; i >= 0; i--)
            {
                if (ReferenceEquals(overrides[i].owner, owner))
                {
                    overrides.RemoveAt(i);
                    removed = true;
                }
            }

            return removed;
        }

        private void PruneDeadOwners()
        {
            for (int i = overrides.Count - 1; i >= 0; i--)
            {
                // Unity's fake-null: a destroyed MonoBehaviour compares equal to null but is
                // still a live reference, so a mode torn down mid-selection can't wedge the
                // reticle on.
                if (overrides[i].owner is Object unityOwner && unityOwner == null)
                {
                    overrides.RemoveAt(i);
                }
            }
        }

        private static Texture2D Load(string name)
        {
            Texture2D texture = Resources.Load<Texture2D>(ResourceFolder + name);
            if (texture == null)
            {
                Debug.LogError($"CursorManager: missing Resources/{ResourceFolder}{name} (run tools/cursor-gen/generate_cursors.py).");
            }

            return texture;
        }
    }
}
